language: python
python:
  - "3.6"

sudo: required

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - echo "No test implemented."

after_success:
  # Push only for push integrations, not pull request.
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

      docker build -t lynlab/lynlab:${TRAVIS_BRANCH} .
      docker push lynlab/lynlab:${TRAVIS_BRANCH}

      docker build -t lynlab/lynlab:latest .
      docker push lynlab/lynlab:latest

      if [ -n "${TRAVIS_TAG}" ]; then
        docker build -t lynlab/lynlab:${TRAVIS_TAG} .
        docker push lynlab/lynlab:${TRAVIS_TAG}
      fi
    fi
