version: '2'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - static
  static:
    build: .
    command: python manage.py collectstatic --no-input
    volumes:
      - /var/www/static/:/var/www/static/
