name: Build Docker Image

on:
  push:
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and push the docker image
      run: |
        docker login --username hellodhlyn --password ${{ secrets.DOCKER_ACCESS_TOKEN }}
        docker build -t lynlab/lynlab:${GITHUB_REF##*/} .
        docker push lynlab/lynlab:${GITHUB_REF##*/}
